//! Low-level core Lanczos algorithm implementations for Krylov subspace methods.
//!
//! Prefer the high-level functions in [`crate::lanczos::solvers`] for normal usage.
//! This module is intended for use cases where fine-grained control over the Lanczos process is required.
//!
//! This module contains the low-level algorithm implementations that power the high-level
//! solvers. These functions are exposed publicly for:
//!
//! - Users who need fine-grained control
//! - Testing and benchmarking purposes
//! - Algorithm experimentation
//!
//! ## Standard API vs Low-level API
//!
//! **Recommended**: Use [`crate::lanczos::solvers::lanczos`] and [`crate::lanczos::solvers::lanczos_two_pass`]
//! for normal usage. These provide a clean, user-friendly interface.
//!
//! **Advanced**: Use functions from this module only if you need access to intermediate
//! results like the Lanczos basis matrix V_k or want to implement custom callbacks.
//!
//! ## Implementation Details
//!
//! This module implements the symmetric Lanczos process for computing f(A)b by projecting
//! the operator A onto a small Krylov subspace, yielding a tridiagonal matrix T_k.
//!
//! Two implementation strategies are provided:
//! 1. **Standard algorithm**: Stores the full orthonormal basis V_k (O(nk) memory)
//! 2. **Two-pass variant**: Avoids basis storage through regeneration (O(n) memory)
//!
//! Both algorithms operate on matrix-free linear operators ([`faer::matrix_free::LinOp`])
//! and use stack-allocated workspaces ([`MemStack`]) for temporary storage. The implementations
//! are generic over complex field types and handle numerical breakdown detection.

// Declare the submodules. The specific implementations will reside in these files.
pub mod lanczos;
pub mod lanczos_two_pass;

use crate::lanczos::error::{LanczosError, LanczosErrorKind};
use faer::traits::math_utils::{add, mul, sub};
use faer::{
    Par,
    dyn_stack::{MemStack, StackReq},
    matrix_free::LinOp,
    prelude::*,
    traits::{ComplexField, RealField},
};

// All the following are common definitions used by both the one-pass and two-pass implementations.

/// Controls the reorthogonalization strategy for the one-pass Lanczos process.
///
/// The standard 3-term recurrence loses orthogonality in finite precision
/// at a rate proportional to `eps * kappa(A)`. Full reorthogonalization
/// restores machine-precision orthogonality at the cost of O(k^2 * n) work.
///
/// Only available for the one-pass algorithm. The two-pass algorithm discards
/// basis vectors and cannot reorthogonalize.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Reorthogonalization {
    /// Standard 3-term recurrence. O(k * n) vector work.
    #[default]
    None,
    /// Full reorthogonalization with DGKS refinement. O(k^2 * n) work.
    Full,
}

/// A read-only, non-owning view of the tridiagonal matrix generated by the Lanczos process.
///
/// This struct provides zero-allocation access to the raw tridiagonal matrix data
/// by referencing existing slices. Its primary use is in callbacks for inspecting the
/// algorithm's state without incurring the performance penalty of data duplication or
/// cache-unfriendly pointer indirection.
#[derive(Debug)]
pub struct TridiagonalSystemView<'a, R: RealField> {
    /// The diagonal elements of the tridiagonal matrix, corresponding to the
    /// sequence of $\alpha_j$ coefficients.
    pub alphas: &'a [R],
    /// The super/sub-diagonal elements, corresponding to the sequence of $\beta_j$
    /// coefficients.
    pub betas: &'a [R],
    /// The number of iterations completed, which defines the actual dimension
    /// of the system, especially in cases of early termination due to breakdown.
    pub steps_taken: usize,
}

/// A callback function invoked at each step of the Lanczos iteration.
///
/// This provides a hook for monitoring convergence, implementing custom termination
/// criteria, or performing other diagnostics.
///
/// # Arguments
/// * `k`: The current iteration number (1-based).
/// * `v_k`: An immutable view of the $n \times k$ basis matrix $\mathbf{V}_k = [\mathbf{v}_1, \dots, \mathbf{v}_k]$
///   generated so far.
/// * `t_k_view`: A non-owning view of the tridiagonal matrix $\mathbf{T}_k$.
///
/// # Returns
/// `true` to continue the iteration, `false` to request an early stop.
pub type LanczosCallback<T> = dyn for<'a> FnMut(
    usize,
    MatRef<'a, T>,
    &'a TridiagonalSystemView<'a, <T as ComplexField>::Real>,
) -> bool;

/// Contains the scalar data defining the low-dimensional projection of the operator.
///
/// This struct holds all data necessary to define the tridiagonal system $\mathbf{T}_k$
/// and is the complete output of the first pass of the two-pass algorithm. It is
/// designed to be lightweight and cloneable.
#[derive(Debug, Clone)]
pub struct LanczosDecomposition<R: RealField> {
    /// The diagonal elements of the tridiagonal matrix ($\alpha_j$).
    pub alphas: Vec<R>,
    /// The super/sub-diagonal elements of the tridiagonal matrix ($\beta_j$).
    /// The element `betas[j-1]` corresponds to $\beta_j$ for $j = 1, \dots, \text{steps\_taken}-1$.
    /// The vector length is always `steps_taken - 1`.
    pub betas: Vec<R>,
    /// The actual number of steps performed before breakdown or completion. This may be
    /// less than the requested number of iterations.
    pub steps_taken: usize,
    /// The L2 norm of the initial vector, $\|\mathbf{b}\|_2$. This value is pre-computed and
    /// stored to avoid recomputation and is required for the final scaling of the
    /// solution vector $\mathbf{x}_k = \mathbf{V}_k f(\mathbf{T}_k) \mathbf{e}_1 \|\mathbf{b}\|_2$.
    pub b_norm: R,
}

/// Contains the complete output of the standard one-pass Lanczos algorithm.
///
/// This structure holds both the orthonormal basis vectors and the full scalar
/// decomposition, representing the complete state of the Lanczos process after $k$ steps.
#[derive(Debug)]
pub struct LanczosOutput<T: ComplexField> {
    /// The matrix $\mathbf{V}_k \in \mathbb{C}^{n \times k}$ whose columns are the orthonormal
    /// Lanczos basis vectors, $[\mathbf{v}_1, \dots, \mathbf{v}_k]$.
    /// This is the structure that incurs the $O(nk)$ memory cost.
    pub v_k: Mat<T>,
    /// The scalar data from the Lanczos process, including $\mathbf{T}_k$ and $\|\mathbf{b}\|_2$.
    pub decomposition: LanczosDecomposition<T::Real>,
}

/// Contains the output of the second pass, including the regenerated basis.
///
/// This struct is exposed only for testing purposes to allow for a direct
/// norm comparison between the stored basis from [`crate::lanczos::algorithms::lanczos::lanczos_standard`] and the
/// regenerated basis.
#[derive(Debug)]
pub struct LanczosPassTwoOutput<T: ComplexField> {
    /// The final approximate solution vector $\mathbf{x}_k$.
    pub x_k: Mat<T>,
    /// The regenerated basis matrix $\mathbf{V}'_k$.
    pub v_k: Mat<T>,
}

/// Computes the tolerance for breakdown detection based on machine epsilon.
///
/// This provides better numerical robustness than hardcoded tolerances.
fn breakdown_tolerance<T: RealField>() -> T {
    // A small multiple of machine epsilon is a standard choice for breakdown detection.
    T::from_f64_impl(f64::EPSILON * 1000.0)
}

/// Computes the [`StackReq`] for a Lanczos iteration.
///
/// Returns the workspace memory requirement for applying the given operator,
/// which can be used to pre-allocate a [`faer::dyn_stack::MemBuffer`] before
/// calling any Lanczos solver.
pub fn lanczos_scratch<T: ComplexField>(operator: &impl LinOp<T>, par: Par) -> StackReq {
    operator.apply_scratch(1, par)
}

/// Performs a single, fully orthogonalized step of the Lanczos recurrence relation.
///
/// This function implements the core three-term recurrence:
/// $\beta_j \mathbf{v}_{j+1} = \mathbf{A}\mathbf{v}_j - \alpha_j \mathbf{v}_j - \beta_{j-1}\mathbf{v}_{j-1}$.
///
/// The implementation fuses the beta-subtraction and dot-product into a single memory
/// pass, reducing the number of vector sweeps from 4 to 3 compared to the naive
/// formulation. The result is written to a pre-allocated mutable view `w` to avoid
/// heap allocations within the iterative loop.
///
/// # Arguments
/// * `operator`: The linear operator $\mathbf{A}$.
/// * `w`: A pre-allocated mutable matrix view for the output vector $\mathbf{w} = \beta_j \mathbf{v}_{j+1}$.
/// * `v_curr`: The current Lanczos vector $\mathbf{v}_j$.
/// * `v_prev`: The previous Lanczos vector $\mathbf{v}_{j-1}$.
/// * `beta_prev`: The previous off-diagonal coefficient $\beta_{j-1}$.
/// * `tolerance`: The breakdown detection tolerance (typically `eps * 1000`).
/// * `par`: The parallelism strategy for the operator application.
/// * `stack`: A [`MemStack`] for temporary allocations required by the operator's `apply` method.
///
/// # Returns
/// A tuple containing $(\alpha_j, \text{Option}<\beta_j>)$. A [`None`] value for $\beta_j$ indicates
/// that a numerical breakdown has occurred ($\beta_j$ is numerically zero), and the iteration
/// should terminate. This happens when the Krylov subspace becomes invariant under $\mathbf{A}$.
#[expect(clippy::too_many_arguments)]
fn lanczos_recurrence_step<T: ComplexField, O: LinOp<T>>(
    operator: &O,
    mut w: MatMut<'_, T>,
    v_curr: MatRef<'_, T>,
    v_prev: MatRef<'_, T>,
    beta_prev: T::Real,
    tolerance: T::Real,
    par: Par,
    stack: &mut MemStack,
) -> (T::Real, Option<T::Real>) {
    // Pass 1: w = A * v_curr. This is typically the most computationally
    // intensive part of the step.
    operator.apply(w.rb_mut(), v_curr, par, stack);

    // Pass 2 (fused): w -= beta_prev * v_prev AND alpha = v_curr^H * w.
    // Fusing these avoids a separate memory pass for the dot product.
    // The original code performed these as two separate passes (subtract, then
    // dot product). By combining them into a single traversal we reduce memory
    // traffic from 4 vector sweeps to 3.
    let beta_prev_scaled = T::from_real_impl(&beta_prev);
    let mut alpha_acc = T::zero_impl();
    zip!(w.rb_mut(), v_prev, v_curr).for_each(|unzip!(w_i, v_prev_i, v_curr_i)| {
        *w_i = sub(w_i, &mul(&beta_prev_scaled, v_prev_i));
        alpha_acc = add(&alpha_acc, &mul(&T::conj_impl(v_curr_i), &*w_i));
    });
    let alpha = T::real_part_impl(&alpha_acc);

    // Pass 3: w -= alpha * v_curr (second orthogonalization step).
    let alpha_scaled = T::from_real_impl(&alpha);
    zip!(w.rb_mut(), v_curr).for_each(|unzip!(w_i, v_curr_i)| {
        *w_i = sub(w_i, &mul(&alpha_scaled, v_curr_i));
    });

    // Norm via faer's stable SIMD norm_l2 (avoids overflow in manual squared-sum).
    let beta = w.rb().norm_l2();

    // Check for numerical breakdown. If beta_j is close to zero, the Krylov
    // subspace is (numerically) invariant under A, and the iteration must stop.
    if beta <= tolerance {
        (alpha, None)
    } else {
        (alpha, Some(beta))
    }
}

/// A lightweight struct to hold the scalar results of a single Lanczos step.
struct LanczosStep<T: ComplexField> {
    /// The diagonal element $\alpha_j$.
    alpha: T::Real,
    /// The off-diagonal element $\beta_j$.
    beta: T::Real,
}

/// A private struct that encapsulates the state of the Lanczos iteration.
///
/// This struct provides a clean, stateful representation of the Lanczos recurrence,
/// abstracting away the low-level vector manipulations. It is designed as an iterator-like
/// object that can be consumed by different high-level algorithm implementations (e.g.,
/// one-pass vs. two-pass). It manages its own work vectors to avoid repeated heap
/// allocations in the main iterative loop. The use of `Mat<T>` instead of [`MatMut`]
/// for vectors means that this struct takes ownership of the vector data.
struct LanczosIteration<'a, T: ComplexField, O: LinOp<T>> {
    /// A reference to the linear operator.
    operator: &'a O,
    /// The previous Lanczos vector, $\mathbf{v}_{j-1}$.
    v_prev: Mat<T>,
    /// The current Lanczos vector, $\mathbf{v}_j$.
    v_curr: Mat<T>,
    /// A reusable work vector for intermediate computations, primarily to hold $\mathbf{A}\mathbf{v}_j$.
    work: Mat<T>,
    /// The previous beta coefficient, $\beta_{j-1}$.
    beta_prev: T::Real,
    /// Cached breakdown tolerance to avoid recomputation per step.
    tolerance: T::Real,
    /// The parallelism strategy for the operator application.
    par: Par,
    /// The current iteration number (0-indexed internally).
    k: usize,
    /// The maximum number of iterations to perform.
    max_k: usize,
}

impl<'a, T: ComplexField, O: LinOp<T>> LanczosIteration<'a, T, O>
where
    T::Real: RealField,
{
    /// Creates a new [`LanczosIteration`] instance and prepares the initial state.
    ///
    /// # Arguments
    /// * `operator`: The linear operator to be used.
    /// * `b`: The initial vector.
    /// * `max_k`: The maximum number of iterations.
    /// * `b_norm`: The pre-computed L2 norm of `b`.
    /// * `par`: The parallelism strategy for operator application.
    ///
    /// # Returns
    /// A [`Result`] containing the new instance or a [`LanczosError`] if the input vector is zero.
    fn new(
        operator: &'a O,
        b: MatRef<'_, T>,
        max_k: usize,
        b_norm: T::Real,
        par: Par,
    ) -> Result<Self, LanczosError> {
        let zero_threshold = breakdown_tolerance::<T::Real>();
        if b_norm <= zero_threshold {
            return Err(LanczosErrorKind::ZeroInputVector.into());
        }

        // Normalize the initial vector efficiently using the pre-computed norm.
        // This avoids a second norm calculation.
        let inv_norm = T::from_real_impl(&T::Real::recip_impl(&b_norm));
        let v1 = b * Scale(inv_norm);

        Ok(Self {
            operator,
            v_prev: Mat::zeros(b.nrows(), 1),
            v_curr: v1,
            work: Mat::zeros(b.nrows(), 1),
            beta_prev: T::Real::zero_impl(),
            tolerance: breakdown_tolerance::<T::Real>(),
            par,
            k: 0,
            max_k,
        })
    }

    /// Performs the next step of the Lanczos iteration and updates the internal state.
    fn next_step(&mut self, stack: &mut MemStack) -> Option<LanczosStep<T>> {
        if self.k >= self.max_k {
            return None;
        }

        // Execute the core recurrence using the pre-allocated work vector.
        let (alpha, beta_option) = lanczos_recurrence_step(
            self.operator,
            self.work.as_mut(),
            self.v_curr.as_ref(),
            self.v_prev.as_ref(),
            T::Real::copy_impl(&self.beta_prev),
            T::Real::copy_impl(&self.tolerance),
            self.par,
            stack,
        );

        self.k += 1;

        match beta_option {
            Some(beta) => {
                // Normalize the next Lanczos vector in-place: v_{j+1} = work / \beta_j
                let inv_beta = T::from_real_impl(&T::Real::recip_impl(&beta));
                zip!(self.work.as_mut()).for_each(|unzip!(w_i)| {
                    *w_i = mul(w_i, &inv_beta);
                });

                // Update state for the next iteration using move semantics.
                // Swapping vectors is a zero-cost operation that avoids cloning large amounts
                // of data, significantly improving performance by reducing memory traffic.
                // The logical flow is: v_prev gets v_curr's data, v_curr gets the newly computed
                // vector from `work`, and `work` gets the old v_prev's allocation to be reused.
                core::mem::swap(&mut self.v_prev, &mut self.v_curr);
                core::mem::swap(&mut self.v_curr, &mut self.work);
                self.beta_prev = T::Real::copy_impl(&beta);

                Some(LanczosStep {
                    alpha,
                    beta: T::Real::copy_impl(&beta),
                })
            }
            None => {
                // Breakdown occurred. The iteration cannot continue. Return the computed alpha
                // and a zero beta to signal termination to the caller.
                Some(LanczosStep {
                    alpha,
                    beta: T::Real::zero_impl(),
                })
            }
        }
    }
}
